In [ ]:
import pandas as pd
import glob
import os
import matplotlib.pyplot as plt
import ast
import numpy as np

C:\Users\INESW\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [ ]:
parent_folder_ICOB_project = os.get.cwd()

### Getting last elite median individuals from each model

#### make median individual from standard GA

In [ ]:
folder_path_standard = parent_folder_ICOB_project + 'GA\\logs_with_best_params\\'

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(folder_path_standard, "*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
standard_GA_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    standard_GA_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
standard_GA_last_elites_ = [] # list of lists to save 
 
for genotype_string in standard_GA_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    standard_GA_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(standard_GA_last_elites_), axis=0)

# convert back to list if needed
median_indi_standardGA = median_coefficients.tolist()

#### make median individual from egalitarian extinction

In [ ]:
folder_path_extinctions = parent_folder_ICOB_project + 'GA_extinctions\\logs_with_best_params\\'

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(folder_path_extinctions, "egalitarian*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
egalitarian_GA_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    egalitarian_GA_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
egalitarian_GA_last_elites_ = [] # list of lists to save 
 
for genotype_string in egalitarian_GA_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    egalitarian_GA_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(egalitarian_GA_last_elites_), axis=0)

# convert back to list if needed
median_indi_egalitarianGA = median_coefficients.tolist()

#### make median individual from elite extinction

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(folder_path_extinctions, "elite*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
elite_GA_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    elite_GA_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
elite_GA_last_elites_ = [] # list of lists to save 
 
for genotype_string in elite_GA_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    elite_GA_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(elite_GA_last_elites_), axis=0)

# convert back to list if needed
median_indi_eliteGA = median_coefficients.tolist()

#### make median individual from weirdo extinction

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(folder_path_extinctions, "weirdo*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
weirdo_GA_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    weirdo_GA_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
weirdo_GA_last_elites_ = [] # list of lists to save 
 
for genotype_string in weirdo_GA_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    weirdo_GA_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(weirdo_GA_last_elites_), axis=0)

# convert back to list if needed
median_indi_weirdoGA = median_coefficients.tolist()

#### make median individual from immigrant extinction

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(folder_path_extinctions, "immigrant*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
immigrant_GA_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    immigrant_GA_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
immigrant_GA_last_elites_ = [] # list of lists to save 
 
for genotype_string in immigrant_GA_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    immigrant_GA_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(immigrant_GA_last_elites_), axis=0)

# convert back to list if needed
median_indi_immigrantGA = median_coefficients.tolist()

### Seeing RMSE on test data for each median individual/model

In [ ]:
test_data_path = parent_folder_ICOB_project + 'parkinsons_CIFOBIO_TEST.csv'

In [ ]:
testdata = pd.read_csv(test_data_path)

In [ ]:
def calculate_fitness_RMSE(individual, data):
    '''
    This function calculates RMSE (measure of fitness) of an
    individual by receiving the individual (as list of coefficients
    where the 1st coefficient is the intercept) as well as the data
    '''
    # Split features and target
    X = data.iloc[:, :-1].values  # all columns except last
    y_true = data.iloc[:, -1].values  # last column

    # Separate intercept and coefficients
    intercept = individual[0]
    coefficients = np.array(individual[1:])

    # Compute predictions: y_pred = intercept + X @ coefficients
    y_pred = intercept + np.dot(X, coefficients)

    # Compute RMSE
    rmse = np.sqrt(np.mean((y_true - y_pred) ** 2))

    # Return RMSE as fitness (lower is better)
    return rmse

#### RMSE on test data standard GA

In [ ]:
calculate_fitness_RMSE(median_indi_standardGA, testdata)

11.06210585341606

#### RMSE on test data egalitarian GA

In [ ]:
calculate_fitness_RMSE(median_indi_egalitarianGA, testdata)

23.31028677101604

#### RMSE on test data elite GA

In [ ]:
calculate_fitness_RMSE(median_indi_eliteGA, testdata)

18.35080505270951

#### RMSE on test data weirdo GA

In [ ]:
calculate_fitness_RMSE(median_indi_weirdoGA, testdata)

18.410489732344296

#### RMSE on test data immigrant GA

In [ ]:
calculate_fitness_RMSE(median_indi_immigrantGA, testdata)

19.728844899517192

### get range of the variable we want to predict to compare RMSE to -TEST DATA

In [ ]:
testdata

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,65.0,0.0,131.429993,0.00698,0.000066,0.00353,0.00402,0.01058,0.02472,0.212,0.01326,0.01488,0.01903,0.03977,0.021019,20.115000,0.66833,0.72550,0.309770,20.797001
1,57.0,1.0,75.862999,0.00215,0.000010,0.00099,0.00121,0.00298,0.01105,0.099,0.00527,0.00651,0.00761,0.01580,0.004715,29.246000,0.25878,0.67205,0.086541,8.164400
2,59.0,0.0,157.649994,0.00435,0.000038,0.00208,0.00225,0.00623,0.01226,0.106,0.00546,0.00661,0.01294,0.01637,0.008735,23.695000,0.60103,0.73761,0.172010,33.661999
3,60.0,0.0,133.770004,0.00566,0.000058,0.00215,0.00238,0.00644,0.04664,0.407,0.02604,0.03044,0.03640,0.07812,0.041021,16.112000,0.58925,0.70404,0.179070,19.343000
4,66.0,1.0,104.379997,0.00545,0.000024,0.00318,0.00254,0.00953,0.01659,0.185,0.00815,0.00910,0.01183,0.02445,0.013904,25.480000,0.47881,0.56572,0.147210,39.737999
5,57.0,1.0,40.847000,0.00278,0.000012,0.00101,0.00143,0.00302,0.01488,0.162,0.00679,0.00771,0.01188,0.02036,0.013499,29.705000,0.36661,0.62620,0.135830,10.858000
6,63.0,0.0,152.330002,0.00298,0.000024,0.00133,0.00176,0.00400,0.03045,0.267,0.01707,0.01976,0.02297,0.05122,0.007180,23.582001,0.47696,0.65385,0.148210,44.089001
7,68.0,1.0,84.499001,0.00469,0.000024,0.00176,0.00202,0.00527,0.02303,0.177,0.00747,0.01067,0.02522,0.02240,0.019954,22.162001,0.58069,0.64194,0.263190,44.174000
8,78.0,0.0,198.360001,0.00366,0.000022,0.00132,0.00191,0.00395,0.06374,0.546,0.03491,0.03752,0.05308,0.10474,0.012137,20.107000,0.39822,0.67975,0.247910,33.806999
9,59.0,0.0,122.550003,0.00557,0.000052,0.00265,0.00294,0.00796,0.01902,0.170,0.00977,0.01210,0.01905,0.02931,0.039428,17.153999,0.72162,0.68865,0.303270,31.733999
10,74.0,1.0,69.319000,0.00723,0.000045,0.00386,0.00405,0.01158,0.04941,0.371,0.02435,0.02859,0.03991,0.07306,0.017077,19.760000,0.59911,0.75862,0.207940,37.429001
11,76.0,0.0,174.389999,0.00456,0.000046,0.00185,0.00240,0.00556,0.02596,0.227,0.01264,0.01750,0.02411,0.03792,0.022216,21.698000,0.60798,0.58208,0.217020,53.959999
12,36.0,1.0,115.610001,0.00421,0.000021,0.00226,0.00215,0.00677,0.01785,0.180,0.00889,0.00879,0.01019,0.02666,0.016035,20.723000,0.62160,0.55373,0.135640,9.892900
13,66.0,0.0,82.369003,0.00951,0.000067,0.00430,0.00567,0.01291,0.04238,0.374,0.01772,0.02255,0.02696,0.05315,0.058350,21.674999,0.53960,0.66587,0.320030,41.241001
14,73.0,1.0,183.690002,0.00478,0.000025,0.00225,0.00278,0.00676,0.03040,0.262,0.01619,0.01849,0.02391,0.04857,0.022544,21.798000,0.54349,0.69211,0.202300,29.031000
15,63.0,0.0,96.343002,0.00403,0.000029,0.00178,0.00181,0.00534,0.02891,0.263,0.01420,0.01697,0.02276,0.04261,0.015500,23.559999,0.51807,0.63926,0.226500,40.355999
16,57.0,1.0,152.889999,0.00350,0.000014,0.00136,0.00111,0.00408,0.01119,0.115,0.00479,0.00592,0.00869,0.01437,0.010296,31.593000,0.45732,0.63480,0.209150,13.876000
17,76.0,0.0,34.398998,0.01034,0.000110,0.00528,0.00453,0.01583,0.03485,0.320,0.01694,0.02230,0.03097,0.05083,0.036295,18.077000,0.66973,0.57979,0.370750,46.389999
18,72.0,0.0,124.639999,0.00332,0.000019,0.00170,0.00177,0.00511,0.02288,0.187,0.01174,0.01356,0.01702,0.03522,0.004654,27.017000,0.44032,0.59028,0.147810,43.523998
19,57.0,0.0,28.257999,0.00411,0.000023,0.00208,0.00263,0.00625,0.01558,0.159,0.00769,0.00941,0.01279,0.02307,0.017281,21.688999,0.44617,0.55473,0.158660,27.826000
20,49.0,0.0,108.879997,0.00847,0.000076,0.00400,0.00502,0.01201,0.04123,0.362,0.02000,0.02286,0.03987,0.06000,0.037581,17.907000,0.61284,0.71879,0.276370,33.202000
21,58.0,0.0,150.800003,0.00793,0.000064,0.00379,0.00385,0.01136,0.03751,0.316,0.02074,0.02222,0.02576,0.06223,0.023637,20.850000,0.47874,0.76801,0.262170,19.316999
22,57.0,1.0,121.550003,0.00385,0.000022,0.00158,0.00190,0.00473,0.02034,0.167,0.01012,0.01203,0.01672,0.03037,0.015937,23.354000,0.51703,0.68279,0.169080,16.542000
23,65.0,0.0,116.360001,0.00527,0.000043,0.00300,0.00262,0.00899,0.03739,0.328,0.02095,0.02113,0.03006,0.06284,0.010446,22.691999,0.46220,0.63591,0.188110,7.000000
24,49.0,0.0,11.890000,0.00821,0.000075,0.00466,0.00480,0.01398,0.05798,0.522,0.03392,0.03678,0.03908,0.10176,0.059858,16.785999,0.69892,0.63665,0.317340,30.660999
25,72.0,0.0,117.669998,0.00444,0.000024,0.00197,0.00224,0.00591,0.01878,0.176,0.00988,0.01072,0.01436,0.02965,0.039547,26.738001,0.39302,0.54446,0.183450,42.903999
26,66.0,1.0,83.302002,0.00502,0.000023,0.00244,0.00248,0.00731,0.01805,0.170,0.00938,0.01029,0.01157,0.02813,0.030484,25.209999,0.51777,0.59539,0.154040,38.450001
27,63.0,0.0,166.330002,0.01137,0.000095,0.00631,0.00500,0.01893,0.08252,0.737,0.04786,0.05212,0.06126,0.14359,0.075578,16.278999,0.56205,0.67865,0.277680,45.021999
28,49.0,0.0,59.835999,0.01389,0.000122,0.00735,0.00844,0.02204,0.06424,0.581,0.03187,0.04090,0.05694,0.09561,0.057268,13.852000,0.70981,0.72414,0.473240,33.324001
29,66.0,0.0,124.480003,0.01035,0.000071,0.00606,0.00435,0.01818,0.04176,0.373,0.02175,0.02089,0.02272,0.06526,0.062269,20.912001,0.58853,0.65956,0.238580,43.104000
30,49.0,0.0,123.370003,0.00466,0.000043,0.00121,0.00204,0.00363,0.01434,0.134,0.00367,0.00590,0.01495,0.01100,0.014458,25.094000,0.70274,0.71440,0.141040,33.522999
31,65.0,0.0,69.428001,0.00487,0.000048,0.00253,0.00300,0.00759,0.02803,0.239,0.01489,0.01780,0.02172,0.04467,0.017138,20.545000,0.53393,0.70709,0.253850,17.340000
32,78.0,0.0,80.348999,0.00531,0.000038,0.00200,0.00186,0.00600,0.01288,0.119,0.00582,0.00731,0.01284,0.01747,0.017211,24.952999,0.41450,0.67882,0.207150,28.952000
33,68.0,0.0,77.347000,0.01891,0.000202,0.01044,0.01018,0.03132,0.04398,0.395,0.02150,0.02867,0.03408,0.06451,0.064367,16.236000,0.80527,0.80126,0.461420,24.681000
34,63.0,0.0,33.339001,0.00346,0.000025,0.00138,0.00152,0.00414,0.03508,0.321,0.01956,0.02177,0.02870,0.05868,0.010784,24.322001,0.45725,0.61828,0.115580,39.366001
35,73.0,0.0,123.830002,0.00505,0.000043,0.00174,0.00268,0.00522,0.02550,0.241,0.01229,0.01553,0.02357,0.03687,0.027668,21.743999,0.52594,0.61330,0.185240,39.480000
36,66.0,1.0,72.414001,0.00779,0.000039,0.00409,0.00378,0.01226,0.04912,0.464,0.02701,0.02955,0.03998,0.08103,0.041527,15.685000,0.64395,0.60096,0.246370,30.148001
37,57.0,1.0,63.504002,0.00441,0.000025,0.00205,0.00211,0.00614,0.02073,0.204,0.01049,0.01116,0.01603,0.03146,0.007775,24.715000,0.49459,0.73717,0.216940,13.940000
38,49.0,0.0,80.819000,0.00484,0.000044,0.00261,0.00268,0.00784,0.04337,0.366,0.02253,0.02610,0.03203,0.06760,0.014154,20.907000,0.71762,0.69351,0.201290,34.490002
39,68.0,0.0,126.260002,0.00746,0.000061,0.00389,0.00325,0.01167,0.01975,0.194,0.01035,0.01074,0.01556,0.03106,0.023634,22.980000,0.47694,0.70263,0.340820,25.622999
40,58.0,1.0,119.339996,0.00261,0.000014,0.00120,0.00135,0.00359,0.01640,0.148,0.00869,0.01020,0.01252,0.02608,0.006789,24.886000,0.42565,0.65390,0.117600,20.490999
41,60.0,0.0,174.850006,0.00461,0.000040,0.00175,0.00233,0.00526,0.03007,0.271,0.01495,0.01789,0.02408,0.04485,0.010888,21.782000,0.52798,0.78366,0.190800,19.832001
42,73.0,1.0,105.580002,0.00615,0.000032,0.00318,0.00323,0.00955,0.01979,0.214,0.01017,0.01162,0.01612,0.03050,0.024450,21.983999,0.46951,0.59931,0.237250,25.938999
43,60.0,0.0,39.827999,0.00610,0.000052,0.00261,0.00286,0.00783,0.05216,0.467,0.02938,0.03224,0.03961,0.08814,0.032185,17.068001,0.55529,0.78269,0.219720,16.517000
44,56.0,1.0,126.739998,0.00262,0.000012,0.00141,0.00154,0.00422,0.01718,0.169,0.00847,0.00854,0.01399,0.02542,0.009126,24.197001,0.46939,0.55563,0.117090,44.796001
45,66.0,1.0,142.389999,0.00450,0.000018,0.00212,0.00244,0.00637,0.03943,0.381,0.02114,0.02563,0.03320,0.06341,0.010975,22.781000,0.43795,0.56241,0.290370,32.000000
46,60.0,0.0,179.770004,0.00591,0.000060,0.00292,0.00371,0.00877,0.06831,0.605,0.03552,0.04470,0.05852,0.10655,0.051974,13.516000,0.64934,0.78146,0.279140,19.889999
47,59.0,0.0,143.610001,0.00605,0.000058,0.00247,0.00336,0.00740,0.01785,0.154,0.00919,0.00988,0.01477,0.02757,0.028140,17.726999,0.71621,0.71389,0.273720,32.890999
48,72.0,0.0,175.300003,0.00803,0.000074,0.00362,0.00499,0.01085,0.03943,0.352,0.01880,0.02601,0.03572,0.05639,0.058686,21.493000,0.56436,0.58201,0.240250,19.049999
49,72.0,0.0,112.300003,0.00703,0.000071,0.00299,0.00357,0.00896,0.02744,0.256,0.01304,0.01755,0.02245,0.03911,0.030947,21.646000,0.52890,0.58000,0.230370,23.605000
50,76.0,0.0,162.350006,0.00623,0.000058,0.00294,0.00210,0.00881,0.02128,0.196,0.01024,0.01208,0.01798,0.03073,0.022328,22.465000,0.67762,0.54961,0.267720,53.167000
51,55.0,0.0,46.584999,0.01065,0.000076,0.00500,0.00616,0.01501,0.02877,0.277,0.01557,0.01895,0.02542,0.04671,0.044893,19.966000,0.62264,0.70606,0.355380,25.389000
52,73.0,1.0,140.550003,0.00464,0.000032,0.00206,0.00248,0.00617,0.02813,0.266,0.01262,0.01768,0.02675,0.03787,0.038115,20.158001,0.61200,0.57712,0.267390,30.936001
53,75.0,0.0,174.360001,0.00961,0.000079,0.00410,0.00511,0.01229,0.07028,0.621,0.03718,0.04264,0.05735,0.11153,0.023746,17.714001,0.53862,0.80699,0.336810,25.770000
54,67.0,0.0,70.775002,0.00404,0.000021,0.00213,0.00224,0.00640,0.04446,0.362,0.02556,0.02577,0.02903,0.07669,0.007908,23.283001,0.47286,0.65193,0.181400,27.666000
55,72.0,0.0,40.652000,0.00353,0.000023,0.00119,0.00159,0.00357,0.02227,0.214,0.01006,0.01337,0.02263,0.03019,0.009438,22.945999,0.53949,0.57243,0.195000,36.869999
56,49.0,0.0,108.879997,0.00454,0.000038,0.00227,0.00263,0.00681,0.03408,0.303,0.01807,0.02122,0.02870,0.05421,0.011270,20.627001,0.57751,0.71511,0.213520,33.202000
57,76.0,0.0,34.402000,0.01527,0.000148,0.00990,0.00695,0.02971,0.07228,0.618,0.04506,0.03935,0.04783,0.13517,0.160180,12.838000,0.72147,0.58619,0.350500,46.389999
58,55.0,0.0,119.430000,0.00348,0.000024,0.00178,0.00191,0.00533,0.03977,0.366,0.02164,0.02182,0.03484,0.06493,0.010534,21.962999,0.46413,0.57414,0.168070,25.032000

In [ ]:
range_value = testdata['19'].max() - testdata['19'].min()

print("Range of target variable:", range_value)

Range of target variable: 46.959999084472656

### get range of the variable we want to predict to compare RMSE to -TRAINING DATA

In [ ]:
train_data_path = parent_folder_ICOB_project + 'parkinsons_CIFOBIO_TRAIN.csv'

In [ ]:
traindata = pd.read_csv(train_data_path)

In [ ]:
traindata

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,66.0,1.0,72.412003,0.00612,0.000035,0.00294,0.00331,0.00882,0.04559,0.419,0.02428,0.02799,0.03385,0.07284,0.025458,18.455000,0.69277,0.64807,0.25326,30.148001
1,78.0,0.0,198.360001,0.00297,0.000018,0.00143,0.00152,0.00429,0.02334,0.203,0.01313,0.01269,0.01870,0.03938,0.010860,20.930000,0.40102,0.62406,0.14084,33.806999
2,59.0,1.0,9.398600,0.00269,0.000014,0.00122,0.00137,0.00366,0.01955,0.176,0.01016,0.01121,0.01267,0.03047,0.006243,24.702999,0.39552,0.68005,0.14989,20.767000
3,78.0,0.0,87.348999,0.00372,0.000024,0.00139,0.00156,0.00418,0.01350,0.220,0.00465,0.00645,0.01293,0.01395,0.028010,26.805000,0.48675,0.62154,0.18389,28.424999
4,66.0,0.0,47.374001,0.00471,0.000035,0.00193,0.00227,0.00580,0.01739,0.191,0.00749,0.00782,0.01162,0.02246,0.030020,26.534000,0.52855,0.57008,0.21104,38.165001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
524,71.0,0.0,188.449997,0.00413,0.000025,0.00164,0.00232,0.00492,0.03865,0.354,0.01788,0.02322,0.03808,0.05363,0.013314,20.642000,0.63232,0.69494,0.25279,53.340000
525,74.0,0.0,92.553001,0.00284,0.000022,0.00126,0.00170,0.00379,0.02607,0.224,0.01461,0.01585,0.02060,0.04383,0.010242,22.143999,0.59353,0.62379,0.14607,26.011999
526,62.0,1.0,29.292999,0.02368,0.000120,0.00970,0.01736,0.02910,0.13666,1.309,0.06377,0.09117,0.11451,0.19130,0.310410,6.653000,0.73547,0.62548,0.55043,27.975000
527,67.0,0.0,18.938999,0.00585,0.000049,0.00284,0.00295,0.00851,0.01960,0.179,0.00919,0.01031,0.01578,0.02758,0.010122,26.469999,0.40905,0.81628,0.16511,18.017000
528,78.0,0.0,127.360001,0.00439,0.000029,0.00170,0.00211,0.00509,0.03648,0.325,0.01835,0.02173,0.03273,0.05504,0.020895,25.589001,0.57642,0.58845,0.13408,29.893999

In [ ]:
range_value = traindata['19'].max() - traindata['19'].min()

print("Range of target variable:", range_value)

Range of target variable: 47.992000579833984

In [ ]:
11.06210585341606 / 46.959999084472656

0.23556443929049714

#

### since standard GA was the best performing, we decided to explore two more different hyperparameter combinations/2 models using the standard GA algorithm

In [ ]:
alternative_hyp_standard_GA_path = parent_folder_ICOB_project + 'standardGA_alternative_hyperparameters\\'

#### make median individual from standard GA alternative 1

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(alternative_hyp_standard_GA_path, "cfg08*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
standard_GA_alternative1_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    standard_GA_alternative1_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
standard_GA_alternative1_last_elites_ = [] # list of lists to save 
 
for genotype_string in standard_GA_alternative1_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    standard_GA_alternative1_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(standard_GA_alternative1_last_elites_), axis=0)

# convert back to list if needed
median_indi_standardGA_alternative1 = median_coefficients.tolist()

In [ ]:
median_indi_standardGA_alternative1

[82.53098935937291,
 0.09928364247734002,
 -2.4849858761495165,
 0.015134232501500738,
 3.610127012855829,
 -1.467365763742491,
 -1.339791772973082,
 -1.3648348024581936,
 -2.1084717899245966,
 1.996765475464113,
 -11.733210537778604,
 0.6573389776724061,
 -4.6589736425002695,
 0.27644987408614585,
 -8.527973073188875,
 -2.187567114837112,
 -1.4790012714988934,
 -9.697640528948657,
 -14.095162879322753,
 -6.026726209410457]

In [ ]:
### RMSE on test data
calculate_fitness_RMSE(median_indi_standardGA_alternative1, testdata)

13.320088451167969

#### make median individual from standard GA alternative 2

In [ ]:
# Get all .txt file paths in the folder
file_paths = glob.glob(os.path.join(alternative_hyp_standard_GA_path, "cfg10*.txt"))

# Load each file into a DataFrame and store in a list
dataframes = [pd.read_csv(file, sep=",") for file in file_paths]

In [ ]:
### get genotypes for last elites of each run 
standard_GA_alternative2_last_elites = []

for run in dataframes:
    best_fitness_last = run.iloc[-1]['best_genotype']
    standard_GA_alternative2_last_elites.append(best_fitness_last)

In [ ]:
### turn genotypes into lists (from string)
standard_GA_alternative2_last_elites_ = [] # list of lists to save 
 
for genotype_string in standard_GA_alternative2_last_elites:
    genotype_list = ast.literal_eval(genotype_string)
    standard_GA_alternative2_last_elites_.append(genotype_list)

In [ ]:
### making the standard GA median final elite

# convert to numpy array and compute median along axis 0 (column-wise)
median_coefficients = np.median(np.array(standard_GA_alternative2_last_elites_), axis=0)

# convert back to list if needed
median_indi_standardGA_alternative2 = median_coefficients.tolist()

In [ ]:
median_indi_standardGA_alternative2

[64.12081463147851,
 0.21912687681661638,
 -2.4687268712138826,
 0.0194196715780912,
 -0.7732309258931634,
 -1.6731876791421258,
 -2.2342214645770135,
 1.2863814295902951,
 0.2734068064724604,
 -5.693060681817007,
 -6.490497357925436,
 -0.9638561061565544,
 -1.7954040738401995,
 -7.541635164782366,
 -3.5814347549855228,
 -1.794387392837788,
 -0.9027932419169956,
 -2.7484185477913163,
 -11.796678513808827,
 -0.6614119780771928]

In [ ]:
### RMSE on test data
calculate_fitness_RMSE(median_indi_standardGA_alternative2, testdata)

20.529717754771